### ISSUE TITLE
FMX?

### ISSUE THREAD

**Issue by alissonrodrigo** [OpenSourceCommunityBrasil/TRscPix#1]
Funciona em projetos firemonkey?

**Comment by Ronierys2** [comment]
ainda não !

talvez na próxima semana que faça a versão para FMX


Roniery Santos Cardoso

Programador de Sistemas

________________________________
De: alissonrodrigo ***@***.***>
Enviado: sexta-feira, 4 de março de 2022 13:09
Para: Ronierys2/TRscPix ***@***.***>
Cc: Subscribed ***@***.***>
Assunto: [Ronierys2/TRscPix] FMX? (Issue #1)


Funciona em projetos firemonkey?

**Comment by alissonrodrigo** [comment]
Ha sim, ele sendo suportado por FMX, um app rodando em celulares eu consigo fazer toda a questão de pagamento com o componente?
Ex: faço uma compra qualquer me gera um codigo de pagamento assim que faço o pagamento libera no app?

**Comment by Ronierys2** [comment]
sim !

quando estiver rodando em fmx poderar fazer isso sim !!

**Comment by Ronierys2** [comment]
https://github.com/OpenSourceCommunityBrasil/TRscPix/releases/tag/3.0
